// Curated list of actively-traded US equities (S&P 500 + NASDAQ 100 + major ETFs).
// Updated manually; avoids rate-limited Finnhub /stock/symbol endpoint.
export interface StockSymbol {
  symbol: string;
  name: string;
  mic: string;
}

export const STATIC_SYMBOLS: StockSymbol[] = [
  // ── Mega-cap tech ──
  { symbol: "AAPL",  name: "Apple Inc.",                            mic: "XNAS" },
  { symbol: "MSFT",  name: "Microsoft Corporation",                 mic: "XNAS" },
  { symbol: "GOOGL", name: "Alphabet Inc. Class A",                 mic: "XNAS" },
  { symbol: "GOOG",  name: "Alphabet Inc. Class C",                 mic: "XNAS" },
  { symbol: "AMZN",  name: "Amazon.com Inc.",                       mic: "XNAS" },
  { symbol: "NVDA",  name: "NVIDIA Corporation",                    mic: "XNAS" },
  { symbol: "META",  name: "Meta Platforms Inc.",                   mic: "XNAS" },
  { symbol: "TSLA",  name: "Tesla Inc.",                            mic: "XNAS" },
  { symbol: "AVGO",  name: "Broadcom Inc.",                         mic: "XNAS" },
  { symbol: "ORCL",  name: "Oracle Corporation",                    mic: "XNYS" },
  { symbol: "ADBE",  name: "Adobe Inc.",                            mic: "XNAS" },
  { symbol: "CRM",   name: "Salesforce Inc.",                       mic: "XNYS" },
  { symbol: "AMD",   name: "Advanced Micro Devices Inc.",           mic: "XNAS" },
  { symbol: "INTC",  name: "Intel Corporation",                     mic: "XNAS" },
  { symbol: "QCOM",  name: "QUALCOMM Incorporated",                 mic: "XNAS" },
  { symbol: "TXN",   name: "Texas Instruments Incorporated",        mic: "XNAS" },
  { symbol: "MU",    name: "Micron Technology Inc.",                mic: "XNAS" },
  { symbol: "AMAT",  name: "Applied Materials Inc.",                mic: "XNAS" },
  { symbol: "LRCX",  name: "Lam Research Corporation",             mic: "XNAS" },
  { symbol: "KLAC",  name: "KLA Corporation",                       mic: "XNAS" },
  { symbol: "NFLX",  name: "Netflix Inc.",                          mic: "XNAS" },
  { symbol: "CSCO",  name: "Cisco Systems Inc.",                    mic: "XNAS" },
  { symbol: "IBM",   name: "International Business Machines",       mic: "XNYS" },
  { symbol: "NOW",   name: "ServiceNow Inc.",                       mic: "XNYS" },
  { symbol: "SNOW",  name: "Snowflake Inc.",                        mic: "XNYS" },
  { symbol: "PLTR",  name: "Palantir Technologies Inc.",            mic: "XNYS" },
  { symbol: "PANW",  name: "Palo Alto Networks Inc.",               mic: "XNAS" },
  { symbol: "CRWD",  name: "CrowdStrike Holdings Inc.",             mic: "XNAS" },
  { symbol: "NET",   name: "Cloudflare Inc.",                       mic: "XNYS" },
  { symbol: "DDOG",  name: "Datadog Inc.",                          mic: "XNAS" },
  { symbol: "ZS",    name: "Zscaler Inc.",                          mic: "XNAS" },
  { symbol: "OKTA",  name: "Okta Inc.",                             mic: "XNAS" },
  { symbol: "MDB",   name: "MongoDB Inc.",                          mic: "XNAS" },
  { symbol: "GTLB",  name: "GitLab Inc.",                           mic: "XNAS" },
  { symbol: "PATH",  name: "UiPath Inc.",                           mic: "XNYS" },
  { symbol: "AI",    name: "C3.ai Inc.",                            mic: "XNYS" },
  { symbol: "BBAI",  name: "BigBear.ai Holdings",                   mic: "XNYS" },
  { symbol: "SOUN",  name: "SoundHound AI Inc.",                    mic: "XNAS" },
  { symbol: "IONQ",  name: "IonQ Inc.",                             mic: "XNYS" },
  { symbol: "RGTI",  name: "Rigetti Computing Inc.",                mic: "XNAS" },
  // ── Fintech / Financial ──
  { symbol: "V",     name: "Visa Inc.",                             mic: "XNYS" },
  { symbol: "MA",    name: "Mastercard Incorporated",               mic: "XNYS" },
  { symbol: "PYPL",  name: "PayPal Holdings Inc.",                  mic: "XNAS" },
  { symbol: "SQ",    name: "Block Inc.",                            mic: "XNYS" },
  { symbol: "COIN",  name: "Coinbase Global Inc.",                  mic: "XNAS" },
  { symbol: "HOOD",  name: "Robinhood Markets Inc.",                mic: "XNAS" },
  { symbol: "SOFI",  name: "SoFi Technologies Inc.",                mic: "XNAS" },
  { symbol: "AFRM",  name: "Affirm Holdings Inc.",                  mic: "XNAS" },
  { symbol: "UPST",  name: "Upstart Holdings Inc.",                 mic: "XNAS" },
  { symbol: "ADYEY", name: "Adyen N.V.",                            mic: "XNAS" },
  // ── Banks ──
  { symbol: "JPM",   name: "JPMorgan Chase & Co.",                  mic: "XNYS" },
  { symbol: "BAC",   name: "Bank of America Corporation",           mic: "XNYS" },
  { symbol: "WFC",   name: "Wells Fargo & Company",                 mic: "XNYS" },
  { symbol: "GS",    name: "The Goldman Sachs Group Inc.",          mic: "XNYS" },
  { symbol: "MS",    name: "Morgan Stanley",                        mic: "XNYS" },
  { symbol: "C",     name: "Citigroup Inc.",                        mic: "XNYS" },
  { symbol: "USB",   name: "U.S. Bancorp",                          mic: "XNYS" },
  { symbol: "PNC",   name: "PNC Financial Services Group",          mic: "XNYS" },
  { symbol: "BK",    name: "The Bank of New York Mellon",           mic: "XNYS" },
  { symbol: "AXP",   name: "American Express Company",              mic: "XNYS" },
  { symbol: "COF",   name: "Capital One Financial Corporation",     mic: "XNYS" },
  { symbol: "DFS",   name: "Discover Financial Services",           mic: "XNYS" },
  { symbol: "SCHW",  name: "The Charles Schwab Corporation",        mic: "XNYS" },
  { symbol: "BLK",   name: "BlackRock Inc.",                        mic: "XNYS" },
  { symbol: "SPGI",  name: "S&P Global Inc.",                       mic: "XNYS" },
  // ── Healthcare / Biotech ──
  { symbol: "JNJ",   name: "Johnson & Johnson",                     mic: "XNYS" },
  { symbol: "UNH",   name: "UnitedHealth Group Incorporated",       mic: "XNYS" },
  { symbol: "PFE",   name: "Pfizer Inc.",                           mic: "XNYS" },
  { symbol: "MRK",   name: "Merck & Co. Inc.",                      mic: "XNYS" },
  { symbol: "ABBV",  name: "AbbVie Inc.",                           mic: "XNYS" },
  { symbol: "LLY",   name: "Eli Lilly and Company",                 mic: "XNYS" },
  { symbol: "BMY",   name: "Bristol-Myers Squibb Company",          mic: "XNYS" },
  { symbol: "AMGN",  name: "Amgen Inc.",                            mic: "XNAS" },
  { symbol: "GILD",  name: "Gilead Sciences Inc.",                  mic: "XNAS" },
  { symbol: "BIIB",  name: "Biogen Inc.",                           mic: "XNAS" },
  { symbol: "REGN",  name: "Regeneron Pharmaceuticals Inc.",        mic: "XNAS" },
  { symbol: "MRNA",  name: "Moderna Inc.",                          mic: "XNAS" },
  { symbol: "BNTX",  name: "BioNTech SE",                           mic: "XNAS" },
  { symbol: "ISRG",  name: "Intuitive Surgical Inc.",               mic: "XNAS" },
  { symbol: "MDT",   name: "Medtronic plc",                         mic: "XNYS" },
  { symbol: "ABT",   name: "Abbott Laboratories",                   mic: "XNYS" },
  { symbol: "TMO",   name: "Thermo Fisher Scientific Inc.",         mic: "XNYS" },
  { symbol: "DHR",   name: "Danaher Corporation",                   mic: "XNYS" },
  { symbol: "CVS",   name: "CVS Health Corporation",                mic: "XNYS" },
  { symbol: "CI",    name: "The Cigna Group",                       mic: "XNYS" },
  { symbol: "HUM",   name: "Humana Inc.",                           mic: "XNYS" },
  { symbol: "TDOC",  name: "Teladoc Health Inc.",                   mic: "XNYS" },
  { symbol: "HIMS",  name: "Hims & Hers Health Inc.",               mic: "XNYS" },
  // ── Consumer / Retail ──
  { symbol: "AMZN",  name: "Amazon.com Inc.",                       mic: "XNAS" },
  { symbol: "WMT",   name: "Walmart Inc.",                          mic: "XNYS" },
  { symbol: "COST",  name: "Costco Wholesale Corporation",          mic: "XNAS" },
  { symbol: "TGT",   name: "Target Corporation",                    mic: "XNYS" },
  { symbol: "HD",    name: "The Home Depot Inc.",                   mic: "XNYS" },
  { symbol: "LOW",   name: "Lowe's Companies Inc.",                 mic: "XNYS" },
  { symbol: "MCD",   name: "McDonald's Corporation",                mic: "XNYS" },
  { symbol: "SBUX",  name: "Starbucks Corporation",                 mic: "XNAS" },
  { symbol: "NKE",   name: "NIKE Inc.",                             mic: "XNYS" },
  { symbol: "LULU",  name: "lululemon athletica inc.",              mic: "XNAS" },
  { symbol: "TJX",   name: "The TJX Companies Inc.",                mic: "XNYS" },
  { symbol: "ROST",  name: "Ross Stores Inc.",                      mic: "XNAS" },
  { symbol: "DG",    name: "Dollar General Corporation",            mic: "XNYS" },
  { symbol: "DLTR",  name: "Dollar Tree Inc.",                      mic: "XNAS" },
  { symbol: "KR",    name: "The Kroger Co.",                        mic: "XNYS" },
  { symbol: "EBAY",  name: "eBay Inc.",                             mic: "XNAS" },
  { symbol: "ETSY",  name: "Etsy Inc.",                             mic: "XNAS" },
  { symbol: "SHOP",  name: "Shopify Inc.",                          mic: "XNYS" },
  // ── Auto ──
  { symbol: "TSLA",  name: "Tesla Inc.",                            mic: "XNAS" },
  { symbol: "F",     name: "Ford Motor Company",                    mic: "XNYS" },
  { symbol: "GM",    name: "General Motors Company",                mic: "XNYS" },
  { symbol: "RIVN",  name: "Rivian Automotive Inc.",                mic: "XNAS" },
  { symbol: "LCID",  name: "Lucid Group Inc.",                      mic: "XNAS" },
  { symbol: "NIO",   name: "NIO Inc.",                              mic: "XNYS" },
  { symbol: "LI",    name: "Li Auto Inc.",                          mic: "XNAS" },
  { symbol: "XPEV",  name: "XPeng Inc.",                            mic: "XNYS" },
  // ── Energy ──
  { symbol: "XOM",   name: "Exxon Mobil Corporation",               mic: "XNYS" },
  { symbol: "CVX",   name: "Chevron Corporation",                   mic: "XNYS" },
  { symbol: "COP",   name: "ConocoPhillips",                        mic: "XNYS" },
  { symbol: "SLB",   name: "SLB",                                   mic: "XNYS" },
  { symbol: "OXY",   name: "Occidental Petroleum Corporation",      mic: "XNYS" },
  { symbol: "PSX",   name: "Phillips 66",                           mic: "XNYS" },
  { symbol: "VLO",   name: "Valero Energy Corporation",             mic: "XNYS" },
  { symbol: "MPC",   name: "Marathon Petroleum Corporation",        mic: "XNYS" },
  { symbol: "EOG",   name: "EOG Resources Inc.",                    mic: "XNYS" },
  { symbol: "PXD",   name: "Pioneer Natural Resources Company",     mic: "XNYS" },
  { symbol: "FSLR",  name: "First Solar Inc.",                      mic: "XNAS" },
  { symbol: "ENPH",  name: "Enphase Energy Inc.",                   mic: "XNAS" },
  { symbol: "NEE",   name: "NextEra Energy Inc.",                   mic: "XNYS" },
  // ── Industrials ──
  { symbol: "GE",    name: "GE Aerospace",                          mic: "XNYS" },
  { symbol: "BA",    name: "The Boeing Company",                    mic: "XNYS" },
  { symbol: "LMT",   name: "Lockheed Martin Corporation",           mic: "XNYS" },
  { symbol: "RTX",   name: "RTX Corporation",                       mic: "XNYS" },
  { symbol: "NOC",   name: "Northrop Grumman Corporation",          mic: "XNYS" },
  { symbol: "GD",    name: "General Dynamics Corporation",          mic: "XNYS" },
  { symbol: "HON",   name: "Honeywell International Inc.",          mic: "XNAS" },
  { symbol: "MMM",   name: "3M Company",                            mic: "XNYS" },
  { symbol: "CAT",   name: "Caterpillar Inc.",                      mic: "XNYS" },
  { symbol: "DE",    name: "Deere & Company",                       mic: "XNYS" },
  { symbol: "UPS",   name: "United Parcel Service Inc.",            mic: "XNYS" },
  { symbol: "FDX",   name: "FedEx Corporation",                     mic: "XNYS" },
  { symbol: "DAL",   name: "Delta Air Lines Inc.",                  mic: "XNYS" },
  { symbol: "UAL",   name: "United Airlines Holdings Inc.",         mic: "XNAS" },
  { symbol: "AAL",   name: "American Airlines Group Inc.",          mic: "XNAS" },
  { symbol: "LUV",   name: "Southwest Airlines Co.",                mic: "XNYS" },
  // ── Communication / Media ──
  { symbol: "DIS",   name: "The Walt Disney Company",               mic: "XNYS" },
  { symbol: "CMCSA", name: "Comcast Corporation",                   mic: "XNAS" },
  { symbol: "T",     name: "AT&T Inc.",                             mic: "XNYS" },
  { symbol: "VZ",    name: "Verizon Communications Inc.",           mic: "XNYS" },
  { symbol: "TMUS",  name: "T-Mobile US Inc.",                      mic: "XNAS" },
  { symbol: "CHTR",  name: "Charter Communications Inc.",           mic: "XNAS" },
  { symbol: "NFLX",  name: "Netflix Inc.",                          mic: "XNAS" },
  { symbol: "SPOT",  name: "Spotify Technology S.A.",               mic: "XNYS" },
  { symbol: "SNAP",  name: "Snap Inc.",                             mic: "XNYS" },
  { symbol: "PINS",  name: "Pinterest Inc.",                        mic: "XNYS" },
  { symbol: "RDDT",  name: "Reddit Inc.",                           mic: "XNYS" },
  { symbol: "RBLX",  name: "Roblox Corporation",                    mic: "XNYS" },
  { symbol: "EA",    name: "Electronic Arts Inc.",                  mic: "XNAS" },
  { symbol: "TTWO",  name: "Take-Two Interactive Software Inc.",    mic: "XNAS" },
  // ── Real Estate ──
  { symbol: "AMT",   name: "American Tower Corporation",            mic: "XNYS" },
  { symbol: "PLD",   name: "Prologis Inc.",                         mic: "XNYS" },
  { symbol: "CCI",   name: "Crown Castle Inc.",                     mic: "XNYS" },
  { symbol: "EQIX",  name: "Equinix Inc.",                          mic: "XNAS" },
  { symbol: "DLR",   name: "Digital Realty Trust Inc.",             mic: "XNYS" },
  { symbol: "O",     name: "Realty Income Corporation",             mic: "XNYS" },
  // ── Consumer staples ──
  { symbol: "PG",    name: "The Procter & Gamble Company",          mic: "XNYS" },
  { symbol: "KO",    name: "The Coca-Cola Company",                 mic: "XNYS" },
  { symbol: "PEP",   name: "PepsiCo Inc.",                          mic: "XNAS" },
  { symbol: "PM",    name: "Philip Morris International Inc.",      mic: "XNYS" },
  { symbol: "MO",    name: "Altria Group Inc.",                     mic: "XNYS" },
  { symbol: "CL",    name: "Colgate-Palmolive Company",             mic: "XNYS" },
  { symbol: "KMB",   name: "Kimberly-Clark Corporation",            mic: "XNYS" },
  { symbol: "GIS",   name: "General Mills Inc.",                    mic: "XNYS" },
  { symbol: "K",     name: "Kellanova",                             mic: "XNYS" },
  { symbol: "HSY",   name: "The Hershey Company",                   mic: "XNYS" },
  { symbol: "MDLZ",  name: "Mondelez International Inc.",           mic: "XNAS" },
  // ── Materials ──
  { symbol: "LIN",   name: "Linde plc",                             mic: "XNAS" },
  { symbol: "APD",   name: "Air Products and Chemicals Inc.",       mic: "XNYS" },
  { symbol: "NEM",   name: "Newmont Corporation",                   mic: "XNYS" },
  { symbol: "FCX",   name: "Freeport-McMoRan Inc.",                 mic: "XNYS" },
  { symbol: "AA",    name: "Alcoa Corporation",                     mic: "XNYS" },
  { symbol: "NUE",   name: "Nucor Corporation",                     mic: "XNYS" },
  // ── Crypto-adjacent / Speculative ──
  { symbol: "MSTR",  name: "MicroStrategy Incorporated",            mic: "XNAS" },
  { symbol: "MARA",  name: "MARA Holdings Inc.",                    mic: "XNAS" },
  { symbol: "RIOT",  name: "Riot Platforms Inc.",                   mic: "XNAS" },
  { symbol: "CLSK",  name: "CleanSpark Inc.",                       mic: "XNAS" },
  { symbol: "HUT",   name: "Hut 8 Corp.",                           mic: "XNAS" },
  // ── Major ETFs ──
  { symbol: "SPY",   name: "SPDR S&P 500 ETF Trust",                mic: "ARCX" },
  { symbol: "QQQ",   name: "Invesco QQQ Trust Series 1",            mic: "XNAS" },
  { symbol: "IWM",   name: "iShares Russell 2000 ETF",              mic: "ARCX" },
  { symbol: "DIA",   name: "SPDR Dow Jones Industrial Average ETF", mic: "ARCX" },
  { symbol: "VOO",   name: "Vanguard S&P 500 ETF",                  mic: "ARCX" },
  { symbol: "VTI",   name: "Vanguard Total Stock Market ETF",       mic: "ARCX" },
  { symbol: "GLD",   name: "SPDR Gold Shares",                      mic: "ARCX" },
  { symbol: "SLV",   name: "iShares Silver Trust",                  mic: "ARCX" },
  { symbol: "TLT",   name: "iShares 20+ Year Treasury Bond ETF",    mic: "ARCX" },
  { symbol: "XLK",   name: "Technology Select Sector SPDR Fund",    mic: "ARCX" },
  { symbol: "XLF",   name: "Financial Select Sector SPDR Fund",     mic: "ARCX" },
  { symbol: "XLE",   name: "Energy Select Sector SPDR Fund",        mic: "ARCX" },
  { symbol: "XLV",   name: "Health Care Select Sector SPDR Fund",   mic: "ARCX" },
  { symbol: "ARKK",  name: "ARK Innovation ETF",                    mic: "ARCX" },
  { symbol: "SQQQ",  name: "ProShares UltraPro Short QQQ",          mic: "XNAS" },
  { symbol: "TQQQ",  name: "ProShares UltraPro QQQ",                mic: "XNAS" },
  { symbol: "UVXY",  name: "ProShares Ultra VIX Short-Term Futures ETF", mic: "ARCX" },
  { symbol: "VIXY",  name: "ProShares VIX Short-Term Futures ETF",  mic: "ARCX" },
].filter((s, i, arr) => arr.findIndex((x) => x.symbol === s.symbol) === i) // dedupe
 .sort((a, b) => a.symbol.localeCompare(b.symbol));
